version: '2.3'
services:
    nginx:
        build: .
        image: ubuntu-nginx-runit
        container_name: ubuntu-nginx-runit
        network_mode: host
        volumes:
            - ./rootfs/etc/service:/etc/service
            - ./rootfs/etc/php/5.6/fpm/php-fpm.conf:/etc/php/5.6/fpm/php-fpm.conf
            - ./rootfs/etc/php/5.6/fpm/pool.d/:/etc/php/5.6/fpm/pool.d/
        environment:
            TEST: test
        ports:
            - 8080:80
