version: '2.3'
services:
    nginx:
        build: .
        image: ubuntu-nginx-runit
        container_name: ubuntu-nginx-runit
        network_mode: host
        volumes:
            - ./rootfs/etc/php/7.2/fpm/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
            - ./rootfs/etc/php/7.2/fpm/pool.d/:/etc/php/7.2/fpm/pool.d/
            - ./rootfs/etc/nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
        environment:
            TEST: test
        ports:
            - 8080:80
