version: '2.3'
services:
    nginx:
        build: .
        image: ubuntu-nginx-runit
        container_name: ubuntu-nginx-runit
        volumes:
            - ./rootfs/etc/php/5.6/fpm/php-fpm.conf:/etc/php/5.6/fpm/php-fpm.conf
            - ./rootfs/etc/php/5.6/fpm/pool.d/:/etc/php/5.6/fpm/pool.d/
            - ./rootfs/etc/nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
            - /.rootfs/var/www/html/index.php:/var/www/html/index.php
        environment:
            TEST: test
        ports:
            - 8081:80
